version: '3.8'
services:
  unabridged:
    image: 'keenanrnicholson/unabridged:latest'
    container_name: unabridged
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      ORIGIN: 'http://localhost:3000'
      TZ: 'America/New_York'
    ports:
      - '3000:3000'
    volumes:
      - ../db:/db
      - ../library:/library