# https://hackernoon.com/a-better-way-to-develop-node-js-with-docker-cd29d3a0093

version: '3'
services:
  dev:
    image: unabridged-dev
    container_name: unabridged-dev
    volumes:
      - nodemodules-unabridged:/app/node_modules
      - ../app:/app
      - ../.audible:/root/.audible
    
    ###### Issue!! TODO: These arent making it to NODE using process.env!
    environment: 
      - NODE_ENV=development
      - AWS_REGION=local
      - AWS_ACCESS_KEY_ID=thisIsaCrazyKeyID
      - AWS_SECRET_ACCESS_KEY=thisisawILdKeyc0d3
      - AWS_DYNAMO_ENDPOINT=http://dynamodb:8000
      - LIBRARY_DYNAMO_TABLE_NAME=unabridged-library
      - PROFILES_DYNAMO_TABLE_NAME=unabridged-profiles
      - DOWNLOADS_DYNAMO_TABLE_NAME=unabridged-downloads
      - CREATE_TABLES=true
    working_dir: /app
    command: sh -c "npm i && npm run dev"
    ports:
      - 5173:5173
    tty: true
    stdin_open: true
    # network_mode: "host"
  dynamodb:
    image: amazon/dynamodb-local
    hostname: dynamodb-local
    container_name: unabridged-dynamodb-local
    environment:
      - AWS_ACCESS_KEY_ID=thisIsaCrazyKeyID
      - AWS_SECRET_ACCESS_KEY=thisisawILdKeyc0d3
    entrypoint: java
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /data"
    restart: always
    volumes:
      - ./database/data:/data
    ports:
      - 8000:8000
volumes:
  nodemodules-unabridged:
    external: true