# https://hackernoon.com/a-better-way-to-develop-node-js-with-docker-cd29d3a0093

version: '2'
services:
  base:
    image: unabridged-dev
    container_name: unabridged-builder
    volumes:
      - nodemodules-unabridged:/app/node_modules
      - ../app:/app
    working_dir: /app
  install:
    extends:
      service: base
    command: npm i
  # build:
  #   extends:
  #     service: install
  #   command: npm run build-db
  # create-bundles:
  #   extends:
  #     service: base
  #   command: npm run create-bundles
volumes:
  nodemodules-unabridged:
    external: true