version: '3.8'
services:
  unabridged:
    image: 'keenanrnicholson/unabridged:local'
    container_name: unabridged
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      ORIGIN: 'http://localhost:5173'
      TZ: 'America/New_York'
    ports:
      - '5173:3000'
    volumes:
      - ../library/db:/db
      - ../library/files:/library
