# https://hackernoon.com/a-better-way-to-develop-node-js-with-docker-cd29d3a0093

version: '3'
services:
  dev:
    image: unabridged-dev
    container_name: unabridged-dev
    volumes:
      - nodemodules-unabridged:/app/node_modules
      - ../app:/app
      - ../app/db:/db
      - ../library:/library

    environment:
      ORIGIN: 'http://localhost:5173'
    
    stop_signal: SIGKILL
    working_dir: /app
    command: npm run dev -- --host
    init: true
    ports:
      - 5173:5173
    tty: true
    stdin_open: true
    # network_mode: "host"

volumes:
  nodemodules-unabridged:
    external: true