# https://hackernoon.com/a-better-way-to-develop-node-js-with-docker-cd29d3a0093

version: '2'
services:
  base:
    image: node:16.17.1-alpine
    container_name: unabridged-builder
    volumes:
      - nodemodules-unabridged:/ui/node_modules
      - ../ui:/ui
    working_dir: /ui
  install:
    extends:
      service: base
    command: npm i
  # build:
  #   extends:
  #     service: base
  #   command: npm run build
  # create-bundles:
  #   extends:
  #     service: base
  #   command: npm run create-bundles
volumes:
  nodemodules-unabridged:
    external: true