version: '3'
services:
  preview:
    image: unabridged-dev
    container_name: unabridged-preview
    volumes:
      - ../node_modules:/app/node_modules
      - ../:/app
      - ../library/db:/db
      - ../library/files:/library

    environment:
      ORIGIN: 'http://localhost:5173'
      TZ: 'America/New_York'

    stop_signal: SIGKILL
    working_dir: /app
    command: bash -c "npm i && npx prisma generate && npm run preview -- --host"
    init: true
    ports:
      - 5173:4173
    tty: true
    stdin_open: true
