# https://hackernoon.com/a-better-way-to-develop-node-js-with-docker-cd29d3a0093

version: '2'
services:
  preview:
    image: unabridged-dev
    container_name: unabridged-preview
    volumes:
      - nodemodules-unabridged:/app/node_modules
      - ../app:/app
      - ../app/db:/db
      - ../library:/library

    environment:
      ORIGIN: 'http://localhost:4173'
      TZ: 'America/New_York'

    stop_signal: SIGKILL
    working_dir: /app
    command: npm run preview -- --host
    init: true
    ports:
      - 4173:4173
    tty: true
    stdin_open: true
    # network_mode: "host"
volumes:
  nodemodules-unabridged:
    external: true