# https://hackernoon.com/a-better-way-to-develop-node-js-with-docker-cd29d3a0093

version: '3'
services:
  dev:
    image: unabridged-dev
    container_name: unabridged-dev
    volumes:
      - nodemodules-unabridged:/app/node_modules
      - ../app:/app
      - ../app/db:/db
      - ../library:/library
    
    ###### Issue!! TODO: These arent making it to NODE using process.env!
    environment: 
      - NODE_ENV=development
    working_dir: /app
    command: sh -c "npm i && npx prisma generate && npm run dev -- --host"
    ports:
      - 5173:5173
    tty: true
    stdin_open: true
    # network_mode: "host"

volumes:
  nodemodules-unabridged:
    external: true