export enum ProcessError {
  NO_ERROR = 'NO_ERROR',
  AUDIBLE_LOCKED = 'AUDIBLE_LOCKED',
  BOOK_NOT_FOUND = 'BOOK_NOT_FOUND',
  CANCELED = 'CANCELED',
  NO_PROFILE = 'NO_PROFILE',
  NO_PROFILE_WITH_AUTHCODE = 'NO_PROFILE_WITH_AUTHCODE',
  NO_FOLDER = 'NO_FOLDER',
  CONVERSION_ERROR = 'CONVERSION_ERROR',
  COULD_NOT_SAVE = 'COULD_NOT_SAVE',
}