# name: Docker Image CI

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:

#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v3
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)




name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3
      
      # Save metadata about this push to be used in the tag and label process below
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: keenanrnicholson/unabridged

      # Setup QEMU for multi-platform compilations
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Setup Buildx which will actually build the images for various architectures
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login to Docker Hub so we can push the created images
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build the image for each platform target
      - name: Build and push with Mongo included
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          target: prod-mongo
          file: docker/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=keenanrnicholson/unabridged:buildcache
          cache-to: type=registry,ref=keenanrnicholson/unabridged:buildcache,mode=max
          
      # Update the Docker Hub description to match the README.md
      - name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: keenanrnicholson/unabridged



          
